CREATE TABLE IF NOT EXISTS users (
    id      BIGSERIAL GENERATED AS IDENTITY PRIMARY KEY,
    email   CHARACTER VARYING NOT NULL,
    name    CHARACTER VARYING NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGSERIAL GENERATED AS IDENTITY PRIMARY KEY,
    user_id     BIGSERIAL NOT NULL,
    name        CHARACTER VARYING NOT NULL,
    description CHARACTER VARYING,
    available   BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_items_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id      BIGSERIAL GENERATED AS IDENTITY PRIMARY KEY,
    start   TIMESTAMP,
    end     TIMESTAMP,
    status  CHARACTER VARYING NOT NULL,
    item_id BIGSERIAL NOT NULL,
    user_id BIGSERIAL NOT NULL,
    CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_bookings_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);